#include "ZedDriver.h"
#include <bits/stdc++.h>
#include <rclcpp/rclcpp.hpp>

#include <signal.h>

#include <sl/Fusion.hpp>
#include <sl/Camera.hpp>

void intHandler(int dum){ 
    rclcpp::shutdown();
}



int main(int argc, char **argv)
{
    signal(SIGINT, intHandler); 

    if (argc < 2) {
		// this file should be generated by using the tool ZED360
		std::cout << "Need a Configuration file in input" << std::endl;
        // RCLCPP_INFO(get_logger("Need a Configuration file in input"),"PCL_SAFETY_LOGGER");	
		return 1;
	}
    
    

    // Read json file containing the configuration of your multicamera setup.    
	std::string json_config(argv[1]);
 


    
    rclcpp::init(argc,argv);
    rclcpp::executors::MultiThreadedExecutor exec;
    rclcpp::NodeOptions options;

    // sensors::ZedDriver zed(options,json_config);


    auto client_node = std::make_shared<sensors::ZedDriver>(options,json_config);
    exec.add_node(client_node);
    exec.spin();


    


}